name: .NET CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # ← New step: make a .sln wrapper for CI
      - name: Prepare solution file
        run: cp src/AktieKoll.slnx src/AktieKoll.sln

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore AktieKoll.sln

      - name: Build
        working-directory: src
        run: dotnet build AktieKoll.sln --no-restore --configuration Release

      - name: Test
        working-directory: src
        run: dotnet test  AktieKoll.sln --no-build --configuration Release --verbosity normal

