name: .NET CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore AktieKoll.slnx

      - name: Build
        working-directory: src
        run: dotnet build AktieKoll.slnx --no-restore --configuration Release

      - name: Test
        working-directory: src
        run: dotnet test  AktieKoll.slnx --no-build --configuration Release --verbosity normal

