name: .NET CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install the .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 3. Restore dependencies by pointing at your .slnx
      - name: Restore dependencies
        run: dotnet restore src/AktieKoll.slnx

      # 4. Build the solution
      - name: Build
        run: dotnet build src/AktieKoll.slnx --no-restore --configuration Release

      # 5. Run all tests
      - name: Test
        run: dotnet test src/AktieKoll.slnx --no-build --verbosity normal
