name: .NET CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install the .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore AktieKoll.slnx   # still restores via your .slnx

      - name: Build
        working-directory: src
        run: dotnet build AktieKoll.slnx --no-restore --configuration Release

      - name: Test
        working-directory: src
        run: dotnet test AktieKoll.Tests/AktieKoll.Tests.csproj --no-build --verbosity normal
