name: Fetch Insider Trades

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore src/FetchTrades/FetchTrades.csproj

      - name: Run fetcher
        env:
          ConnectionStrings__PostgresConnection: ${{ secrets.POSTGRES_CONNECTION }}
          
        run: dotnet run --project src/FetchTrades/FetchTrades.csproj
