name: Update Company List

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

permissions:
  contents: read

jobs:
  update-companies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore src/FetchCompanies/FetchCompanies.csproj
      
      - name: Fetch and Save Companies
        env:
          EOD_API_TOKEN: ${{ secrets.EOD_API_TOKEN }}
          ConnectionStrings__PostgresConnection: ${{ secrets.POSTGRES_CONNECTION }}
        run: dotnet run --project src/FetchCompanies/FetchCompanies.csproj